server:
  port: 8080
spring:
  ###数据库相关连接
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.202.58:3306/wmh?useUnicode=true&characterEncoding=UTF-8
####打印MyBatias日志