###服务启动端口号
server:
  port: 8080
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://39.105.202.58:3306/wmh?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

####打印MyBatias日志
logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.mayikt.member.mapper: DEBUG
